main: net.tfminecraft.dowsing.DowsingMain
api-version: '1.21.10'
name: Dowsing
version: '${project.version}'
author: Drefvelin

depend: [TLibs, SimpleFactions, MMOItems, MythicLib, ItemsAdder]
softdepend: [Magic]

commands:
  dowsing:
    usage: /<command>
    description: Manage and inspect Dowsing resource nodes.
